name: DanceDanceDance

on:
  push:
    paths:
      - 'mambo.m3u'
      - 'halay.m3u'
      - 'rhumba.m3u'
      - 'tango.m3u'

jobs:
  update-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v3  # Updated checkout action

      - name: Merge lists
        run: |
          echo '#EXTM3U x-tvg-url="https://sty.ink/epgp3"' > latino.m3u
          
          # Append content from each playlist file, skipping the first line
          awk 'NR>1' tango.m3u >> latino.m3u
          awk 'NR>1' halay.m3u >> latino.m3u
          awk 'NR>1' rhumba.m3u >> latino.m3u
          awk 'NR>1' mambo.m3u >> latino.m3u

      - name: Configure Git
        run: |
          # Set GitHub Actions bot as the commit author
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Force Sync with Remote Repo
        run: |
          git fetch origin main  # Get latest remote changes
          git reset --hard origin/main  # Overwrite local changes with remote version
          git pull origin main --rebase  # Ensure local repo is fully synced

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add latino.m3u
          git commit -m "Auto merge"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/7li8li/chacha.git