name: Update ts-list.m3u Parameters

on:
  push:
    # Trigger workflow on changes to ts-config.env
    paths:
      - 'ts-config.env'

jobs:
  update-parameters:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Read the environment variables from ts-config.env and ts-preconfig.env
    - name: Load environment variables
      run: |
        # Export the new parameters from ts-config.env
        export $(grep -v '^#' ts-config.env | xargs)
        # Export the old parameters from ts-preconfig.env
        export $(grep -v '^#' ts-preconfig.env | xargs)

    # Step 3: Update ts-list.m3u based on the parameters
    - name: Update ts-list.m3u
      run: |
        # Backup the original file
        cp ts-list.m3u ts-list.m3u.bak

        # Replace the old parameters with the new ones in ts-list.m3u
        sed -i "s|$OLD_PARAM1|$NEW_PARAM1|g" ts-list.m3u
        sed -i "s|$OLD_PARAM2|$NEW_PARAM2|g" ts-list.m3u
        sed -i "s|$OLD_PARAM3|$NEW_PARAM3|g" ts-list.m3u
        sed -i "s|$OLD_PARAM4|$NEW_PARAM4|g" ts-list.m3u

    # Step 4: Update ts-preconfig.env with the new parameters
    - name: Update ts-preconfig.env
      run: |
        # Backup the old ts-preconfig.env
        cp ts-preconfig.env ts-preconfig.env.bak

        # Replace the old parameters with the new ones in ts-preconfig.env
        sed -i "s|$OLD_PARAM1|$NEW_PARAM1|g" ts-preconfig.env
        sed -i "s|$OLD_PARAM2|$NEW_PARAM2|g" ts-preconfig.env
        sed -i "s|$OLD_PARAM3|$NEW_PARAM3|g" ts-preconfig.env
        sed -i "s|$OLD_PARAM4|$NEW_PARAM4|g" ts-preconfig.env

    # Step 5: Commit and push the changes
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Add updated files
        git add ts-list.m3u ts-preconfig.env

        # Commit the changes
        git commit -m "Update ts-list.m3u and ts-preconfig.env with new parameters"

        # Push the changes back to the repository
        git push
      env:
        # Pass GitHub token to authenticate push
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
