name: IPTV Liste Birleştirme
on:
  push:
    paths:
      - 'iptvts.m3u'
      - 'iptvg.m3u'
jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v2

      - name: IPTV Listelerini Birleştir
        run: |
          echo "#EXTM3U" > iptvr.m3u
          tail -n +2 iptvts.m3u >> iptvr.m3u
          tail -n +2 iptvg.m3u >> iptvr.m3u

      - name: Güncellenmiş Dosyayı Commit Et
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add iptvr.m3u
          git commit -m "Oto güncelleme"
          git push
