name: Update TS List
on:
  push:
    paths:
      - 'configts'
      - 'preconfigts'
      - 'iptvts.m3u'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Load Previous Parameters
        run: |
          source preconfigts
          echo "OLD_PARAM1=$OLD_PARAM1"
          echo "OLD_PARAM2=$OLD_PARAM2"
          echo "OLD_PARAM3=$OLD_PARAM3"
          echo "OLD_PARAM4=$OLD_PARAM4"

      - name: Load New Parameters
        run: |
          source configts
          echo "NEW_PARAM1=${NEW_PARAM1:-EMPTY}"
          echo "NEW_PARAM2=${NEW_PARAM2:-EMPTY}"
          echo "NEW_PARAM3=${NEW_PARAM3:-EMPTY}"
          echo "NEW_PARAM4=${NEW_PARAM4:-EMPTY}"

      - name: Verify IPTV File Before Update
        run: cat iptvts.m3u || echo "iptvts.m3u is empty!"

      - name: Update IPTV List
        run: |
          if [ -s iptvts.m3u ]; then
            sed -i "s|$OLD_PARAM1|${NEW_PARAM1:-$OLD_PARAM1}|g" iptvts.m3u
            sed -i "s|$OLD_PARAM2|${NEW_PARAM2:-$OLD_PARAM2}|g" iptvts.m3u
            sed -i "s|$OLD_PARAM3|${NEW_PARAM3:-$OLD_PARAM3}|g" iptvts.m3u
            sed -i "s|$OLD_PARAM4|${NEW_PARAM4:-$OLD_PARAM4}|g" iptvts.m3u
          else
            echo "iptvts.m3u is empty! Update aborted." >> error.log
          fi

      - name: Verify IPTV File After Update
        run: cat iptvts.m3u || echo "iptvts.m3u remained empty!"

      - name: Update Previous Config File
        run: |
          echo "OLD_PARAM1=${NEW_PARAM1:-$OLD_PARAM1}" > preconfigts
          echo "OLD_PARAM2=${NEW_PARAM2:-$OLD_PARAM2}" >> preconfigts
          echo "OLD_PARAM3=${NEW_PARAM3:-$OLD_PARAM3}" >> preconfigts
          echo "OLD_PARAM4=${NEW_PARAM4:-$OLD_PARAM4}" >> preconfigts

      - name: Commit and Push Updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add iptvts.m3u preconfigts
          git commit -m "Auto update: Parameters changed"
          git push