name: IPTVR Liste Birleştir
on:
  push:
    paths:
      - 'iptvts.m3u'
      - 'iptvg.m3u'
jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v2

      - name: Listeleri Birleştir
        run: |
          echo "#EXTM3U" > iptvr.m3u  # Yeni listenin başına #EXTM3U ekler
          tail - n +2 iptvts.m3u >> iptvr.m3u  # İlk satır hariç tüm içeriği ekler
          tail - n +2 iptvg.m3u >> iptvr.m3u  # İlk satır hariç tüm içeriği ekler

      - name: Güncellenmiş Dosyayı Commit Et
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add iptvr.m3u
          git commit -m "Auto update"
          git push
