name: IPTVR List
on:
  push:
    paths:
      - 'iptvts.m3u'
      - 'iptvg.m3u'
jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Clonning
        uses: actions/checkout@v2

      - name: Merge lists
        run: |
          echo "#EXTM3U" > iptvr.m3u
          awk 'NR>1' iptvg.m3u >> iptvr.m3u
          awk 'NR>1' iptvts.m3u >> iptvr.m3u

      - name: Commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add iptvr.m3u
          git commit -m "Auto merge"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/7li8li/chacha.git